core/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = "core"
urlpatterns = [
    path("", views.PlaceIndexView.as_view(), name="index"),
    path("about/", TemplateView.as_view(template_name="core/about.html"), name="about"),

    #User Detail
    path("user/<int:pk>/", views.UserDetailView.as_view(), name="user_detail"),

    #Place CRUD
    path("place/<int:pk>/", views.PlaceDetailView.as_view(), name="place_detail"),
    path("place/add", views.PlaceCreateView.as_view(), name="place_add"),
    path(
        "place/update/<int:pk>/", views.PlaceUpdateView.as_view(), name="place_update"
    ),
    path(
        "place/delete/<int:pk>/", views.PlaceDeleteView.as_view(), name="place_delete"
    ),

    #Password CRUD
    path(
        "code/<int:pk>/", views.CodeDetailView.as_view(), name="code_detail"
    ),
    path(
        "code/add/<int:pk>/",
        views.CodeAddView.as_view(),
        name="code_add",
    ),
    path(
        "code/update/<int:pk>/", views.CodeUpdateView.as_view(), name="code_update"
    ),
    path(
        "code/delete/<int:pk>/", views.CodeDeleteView.as_view(), name="code_delete"
    ),

    #Comment CRUD
    #I don't think we need a comment_detail view
    path(
        "comment/add/<int:pk>/",
        views.CommentAddView.as_view(),
        name="comment_add",
    ),
    path(
        "comment/update/<int:pk>/", views.CommentUpdateView.as_view(), name="comment_update"
    ),
    path(
        "comment/delete/<int:pk>/", views.CommentDeleteView.as_view(), name="comment_delete"
    ),


    #Vote for a code - these two function views only accept post requests
    path(
        "code/<int:pk>/worked", views.WorkedView.as_view(), name="code_worked"
    ),
    path(
        "code/<int:pk>/notworked", views.NotWorkedView.as_view(), name="code_notworked"
    ),

    
]

pnp/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('',include('core.urls')),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings

# Create your models here.
class Place(models.Model):
    name = models.CharField(max_length=255)
    long = models.DecimalField(max_digits=23, decimal_places=20)
    lat = models.DecimalField(max_digits=23, decimal_places=20)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class CodeType(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Code(models.Model):
    value = models.CharField(max_length=255)
    code_type = models.ForeignKey(CodeType, on_delete=models.RESTRICT)
    place = models.ForeignKey(Place, on_delete=models.RESTRICT)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='owner')
    users = models.ManyToManyField(settings.AUTH_USER_MODEL, through='Vote')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.value

class Vote(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    code = models.ForeignKey(Code, on_delete=models.CASCADE)
    worked = models.BooleanField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Comment(models.Model):
    text = models.TextField()
    code = models.ForeignKey(Code, on_delete=models.RESTRICT)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # commenting this out for now - the textfield is giving some sort of
    # error, and I'm not sure we need this anyway.
    # def __str__(self):
    #    self.text

core/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from .models import Place, Code, Comment, Vote
from django.contrib.auth.models import User
from django.urls import reverse, reverse_lazy
from core.owner import OwnerCreateView, OwnerDeleteView, OwnerDetailView, OwnerListView, OwnerDeleteView, OwnerUpdateView


# Create your views here.
def home(request):
    return render(request, "core/home.html", {})


#######
# User Detail
#######
class UserDetailView(generic.DetailView):
    model = User

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Change the name of the user context variable here
        context['profile_user'] = context.pop('user')
        return context


#######
# Places
#######
class PlaceIndexView(generic.ListView):
    model = Place


class PlaceDetailView(generic.DetailView):
    model = Place

class PlaceCreateView(OwnerCreateView):
    model = Place
    fields = ['name','long','lat']
    success_url = reverse_lazy("core:index")


class PlaceUpdateView(OwnerUpdateView):
    model = Place
    fields = ['name','long','lat']
    success_url = reverse_lazy("core:index")

class PlaceDeleteView(OwnerDeleteView):
    model = Place
    success_url = reverse_lazy("core:index")

########
# Codes
########
class CodeDetailView(generic.DetailView):
    model = Code

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        this_code = context["code"]
        context["num_yes_votes"] = Vote.objects.filter(code=this_code).filter(worked=True).count()
        context["num_no_votes"] = Vote.objects.filter(code=this_code).filter(worked=False).count()
        return context

class CodeAddView(OwnerCreateView):
    model = Code
    fields = ['value','code_type']

    def get_success_url(self):
        return reverse_lazy("core:place_detail", kwargs={"pk": self.object.place.id})

    def form_valid(self, form):
        form.instance.place_id = self.kwargs.get('pk')
        return super(CodeAddView, self).form_valid(form)

class CodeUpdateView(OwnerUpdateView):
    model = Code
    fields = ['value','code_type']
    
    def get_success_url(self):
        return reverse_lazy("core:place_detail", kwargs={"pk": self.object.place.id})
    
    #we don't need to do the form_valid thing here. It'll just keep the existing foreign key id

class CodeDeleteView(OwnerDeleteView):
    model = Code
    
    def get_success_url(self):
        return reverse_lazy("core:place_detail", kwargs={"pk": self.object.place.id})


########
# Votes
########
class WorkedView(OwnerCreateView):
    model = Vote
    fields = []
    template_name = 'core/code_worked.html'

    def get_success_url(self):
        return reverse_lazy("core:code_detail", kwargs={"pk": self.object.code.id})

    def form_valid(self, form):
        form.instance.code_id = self.kwargs.get('pk')
        form.instance.worked=True
        return super(WorkedView, self).form_valid(form)

class NotWorkedView(OwnerCreateView):
    model = Vote
    fields = []
    template_name = 'core/code_not.html'

    def get_success_url(self):
        return reverse_lazy("core:code_detail", kwargs={"pk": self.object.code.id})

    def form_valid(self, form):
        form.instance.code_id = self.kwargs.get('pk')
        form.instance.worked=False
        return super(NotWorkedView, self).form_valid(form)

########
# Comments
########


class CommentAddView(OwnerCreateView):
    model = Comment
    fields = ['text']

    def get_success_url(self):
        return reverse_lazy("core:code_detail", kwargs={"pk": self.object.code.id})

    def form_valid(self, form):
        form.instance.code_id = self.kwargs.get('pk')
        return super(CommentAddView, self).form_valid(form)


class CommentUpdateView(OwnerUpdateView):
    model = Comment
    fields = ['text']
    
    def get_success_url(self):
        return reverse_lazy("core:code_detail", kwargs={"pk": self.object.code.id})


class CommentDeleteView(OwnerDeleteView):
    model = Comment
    
    def get_success_url(self):
        return reverse_lazy("core:code_detail", kwargs={"pk": self.object.code.id})

core/templates/core/about.html
{% extends 'base.html' %}

{% block content %}


<h1>Welcome to 💩🧑‍💻!</h1>

<p>The name PooPer comes from two things that we want to help you do while 
    you're away from home: <strong>Poo</strong>p and <strong>Per</strong>use (i.e. use the internet).</p>

<p>Please use this site responsibly! By using this site, you commit to following
    businesses' rules about bathroom and wifi use... and don't flush anything other than toilet paper!
    
</p>
{% endblock %}

core/templates/core/code_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<h1>Deleting a Password</h1>
<form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    {{ form.as_p }}
    <input type="submit" value="Confirm">
</form>

<a href="{% url 'core:place_detail' object.place.id %}">Back</a>

{% endblock %}

core/templates/core/code_detail.html
{% extends 'base.html' %}

{% block content %}


<h1>{{ code.value }}</h1>
<h2>{{ code.code_type.name}} for <a href="{% url 'core:place_detail' code.place.id %}">{{code.place.name}}</a></h2>
<h2>{{ code.comment_set.all|length}} comment{{ code.comment_set.all|pluralize }}</h2>

<h3>{{ code.vote_set.all | length}} votes: {{ num_yes_votes }} worked, {{ num_no_votes }} didn't work.</h3>


<h3>Did this code work for you? 
        (<a href="{% url 'core:code_worked' code.id %}">Yes</a> / <a href="{% url 'core:code_notworked' code.id %}">No</a>)
</h3>

<div class="card-container">
    {% for c in code.comment_set.all %}
    <div class="comment-card">
        {{ c.text }}
        <hr>
        {% if user.is_authenticated and user.id == c.owner.id %}
        <a href="{% url 'core:comment_update' c.id %}">
            (edit)
        </a> 
        | 
        <a href="{% url 'core:comment_delete' c.id %}">
            (delete)
        </a>

        {% else %}
        <p>Submitted by <a href="{% url 'core:user_detail' c.owner.id %}">{{ c.owner.username }}</a></p>

        {% endif %}

    </div>
    {% endfor %}
</div>



<a href="{% url 'core:comment_add' code.id %}">New Comment</a> | 
<a href="{% url 'core:place_detail' code.place.id %}">Back</a>
{% endblock %}

core/templates/core/code_form.html
{% extends 'base.html' %}


{% block content %}
<h1>Add a new password.</h1>

        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
        <button type="submit">Save Place</button>
    </form>
{% endblock %}

core/templates/core/code_notworked.html
{% extends 'base.html' %}


{% block content %}
<h1>Click to confirm - this code did not work for you?</h1>

        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
        <button type="submit">Confirm</button>
    </form>
{% endblock %}

core/templates/core/code_worked.html
{% extends 'base.html' %}


{% block content %}
<h1>Click to confirm - this code worked for you?</h1>

        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
        <button type="submit">Yes</button>
    </form>
{% endblock %}

core/templates/core/comment_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<h1>Deleting a Comment</h1>
<form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    {{ form.as_p }}
    <input type="submit" value="Confirm">
</form>

<a href="{% url 'core:code_detail' object.code.id %}">Back</a>

{% endblock %}

core/templates/core/comment_form.html
{% extends 'base.html' %}


{% block content %}
<h1>Add a new comment.</h1>

        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
        <button type="submit">Save comment</button>
    </form>
{% endblock %}

core/templates/core/home.html
{% extends 'base.html' %}





{% block content %}


        <h1>Hi! If you need to poop or peruse, you've come to the right place =)</h1>


{% endblock %}

core/templates/core/password_form.html
{% extends 'base.html' %}


{% block content %}
<h1>Add a new password.</h1>

        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
        <button type="submit">Save Place</button>
    </form>
{% endblock %}

core/templates/core/place_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<h1>Deleting a place</h1>
<form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    {{ form.as_p }}
    <input type="submit" value="Confirm">
</form>

<a href="{% url 'core:index' %}">Back</a>

{% endblock %}

core/templates/core/place_detail.html
{% extends 'base.html' %}

{% block content %}

{% if place.code_set.all|length > 0 %}
<h1>{{ place.name }} has {{ place.code_set.all |length}} password{{ p.code_set.all|pluralize }}</h1>
<p>Click on a password below to view comments<p>
<table>
    <tr>
        <th>Type</th>
        <th>Password</th>
        <th>Submitted By</th>
        <th>Top Comment</th>
        <th>All Comments</th>
        <th>Edit</th>
        <th>Delete</th>
    </tr>
    {% for p in place.code_set.all %}
    <tr>
        <td>{{ p.code_type.name }}</td>
        <td>{{ p.value }}</td>
        <td>{{ p.owner.username }}</td>
        <td>"{{ p.comment_set.first.text}}"</td>
        <td>
            <a href="{% url 'core:code_detail' p.id %}">
             (Read all {{ p.comment_set.all|length}} comment{{ p.comment_set.all|pluralize }})
            </a>
        </td>
        <td>
            {% if user.is_authenticated and user.id == p.owner.id %}
            <a href="{% url 'core:code_update' p.id %}">
                (edit)
            </a>
            {% endif %}
        </td>
        <td>
            {% if user.is_authenticated and user.id == p.owner.id %}
            <a href="{% url 'core:code_delete' p.id %}">
                (delete)
            </a>
            {% endif %}
        </td>
    </tr>
    {% endfor %}
</table>
</ul>
{% endif %}
<a href="{% url 'core:code_add' place.id %}">Submit a new password</a> | 
<a href="{% url 'core:index' %}">Back</a>
{% endblock %}

core/templates/core/place_form.html
{% extends 'base.html' %}

{% block head_content %}
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" />
    <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>
    <style>
        #map { height: 500px; width: 100%; }
    </style>
{% endblock %}

{% block content %}
<h1>Add a new place.</h1>
<p>Type a name for the place here, then click on the map below to place your pin.</p>
    <form method="post">
            {% csrf_token %}
        <label for="name">Place Name:</label>
        <input type="text" id="name" name="name" value="{{ form.name.value|default:'' }}" required>

        <input type="text" id="lat" name="lat" value="{{ form.lat.value|default:'' }}" required hidden>

        <input type="text" id="long" name="long" value="{{ form.long.value|default:'' }}" required hidden>

        <button type="submit">Save Place</button>
    </form>
    <div id="map"></div>

    <script>
        var map = L.map('map').setView([39, -77], 10);
        L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            attribution: '&copy; OpenStreetMap contributors'
        }).addTo(map);

        var marker;

        function updateMarker(lat, lng) {
            if (marker) {
                marker.setLatLng([lat, lng]);
            } else {
                marker = L.marker([lat, lng], { draggable: true }).addTo(map);
                marker.on('dragend', function(e) {
                    var position = marker.getLatLng();
                    document.getElementById('lat').value = position.lat;
                    document.getElementById('long').value = position.lng;
                });
            }
            document.getElementById('lat').value = lat;
            document.getElementById('long').value = lng;
        }

        map.on('click', function(e) {
            updateMarker(e.latlng.lat, e.latlng.lng);
        });

        {% if form.lat.value and form.long.value %}
            updateMarker({{ form.lat.value }}, {{ form.long.value }});
            map.setView([{{ form.lat.value }}, {{ form.long.value }}], 10);
        {% endif %}
    </script>
{% endblock %}

core/templates/core/place_list.html
{% extends 'base.html' %}

{% block head_content %}
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" />
    <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>
    <style>
        #map { height: 500px; width: 100%; }
    </style>
{% endblock %}

{% block content %}

    Click on a place to get started

    
    <h2>Want to add a new place? <a href="{% url 'core:place_add' %}">Click
            Here</a></h2>
    <div id="map"></div>
    <script>
        var map = L.map('map').setView([39, -77], 10);
        L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            attribution: '&copy; OpenStreetMap contributors'
        }).addTo(map);

        var places = [
            {% for place in place_list %}
                {
                    lat: {{ place.lat }},
                    lng: {{ place.long }},
                    url: "{% url 'core:place_detail' place.id %}",
                    edit_url: "{% url 'core:place_update' place.id %}",
                    del_url: "{% url 'core:place_delete' place.id %}",
                    name: "{{ place.name }}"
                },
            {% endfor %}
        ];

        places.forEach(function(place) {
            var marker = L.marker([place.lat, place.lng]).addTo(map);
            var popupContent = `
                <a href="${place.url}"> 
                ${place.name} 
                </a>
                <a href="${place.edit_url}">
                (edit)
                </a>
                <a href="${place.del_url}">
                (delete)
                </a>
                `;
            marker.bindPopup(popupContent);
        });
    </script>

{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
<meta charset="utf-8">
<title>{% block title %}💩🧑‍💻{% endblock %}</title>
<link href="{% static "base.css" %}" rel="stylesheet">
<script src="{% static "init.js" %}"></script>
{% block head_content %}
{% endblock %}
</head>
<body>
    <header>
        <h1>PooPer (a.k.a <strong>Poo</strong>p 'n <strong>Per</strong>use)</h1>
        <p id="tagline"><em>for when you gotta go</em> 💩 <em>or you gotta know</em> 🧑‍💻</p>


    </header>
    <nav>
        <div class="left-links">
                <a href="{% url 'core:index' %}">
                    Home
                </a>



                <a href="{% url 'core:about' %}">
                    About
                </a>
            </div>
            <div class="right-links">
            {% if user.is_authenticated %}

                <a href="{% url 'core:user_detail' user.id %}">{{ user.username }}</a>


                    <form action="{% url 'account_logout' %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="next" value="{{ request.path }}">
                        <button type="submit">Log Out</button>
                    </form>

            {% else %}

                <a href="{% url 'account_login' %}?next={{ request.path }}">(Login)</a>

            {% endif %}
            </div>
    </nav>

<main>
    {% block content %}


    {% endblock %}
</main>
<footer>
    <div id="credits">
        <p>Created by Chris Jones and Krista O'Connell</p>
    </div>
</footer>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}


<h1>Chris and Jeff's DJ4E Projects</h1>

<main>
<ul>
  <li><a href="viewsbasics/">Views Basics</a></li>
  <li><a href="dtl/">Django Template Language</a></li>
  <li><a href="polls/">Polls App</a></li>
  <li><a href="todo/">ToDo App</a></li>
  <li><a href="cosmo/">Cosmetology Scheduling App</a></li>
</ul>
</main>
    {% endblock %}